all:
	gcc file.c
	gcc -o cat cat.c
	gcc -o cat1 cat1.c
	gcc -o date date.c
	gcc -o date1 date1.c
	gcc -o ls ls.c
	gcc -o ls1 ls1.c
	gcc -o mkdir mkdir.c
	gcc -o mkdir1 mkdir1.c
	gcc -o rm rm.c
	gcc -o rm1 rm1.c

run: 
	./a.out

